patches/server/0056-Faster-redstone-torch-rapid-clock-removal.patch
patches/server/0061-Allow-disabling-component-selector-resolving-in-book.patch

Disabling this function prevents some exploits (even the newly discovered exploit using books).

Allow disabling component selector resolving in books and update patch notes

---

patches/server/0065-Backport-SPIGOT-5428-Better-handling-of-some-ItemMet.patch

Avoid using items with invalid effects and patterns to disconnect players.
Original patch: https://github.com/PaperMC/Paper/blob/ver/1.13.2/Spigot-Server-Patches/0447-Backport-SPIGOT-5428-Better-handling-of-some-ItemMet.patch <- NOTE: Fixes for CraftMetaMap/Potion not implemented due to non-extension of color implementation in their classes in 1.8.

Backport "Better handling of some ItemMeta" patch

---

patches/server/0066-Fix-issue-with-ProtocolSupport.patch

Paper has already added a great deal of this patch, it just hasn't added the workaround for ProtocolSupport to work properly.
https://github.com/TacoSpigot/TacoSpigot/blob/version/1.8.8/PaperSpigot-Server-Patches/0018-Limit-the-length-of-buffered-bytes-to-read.patch

Backport TacoSpigot fix to ProtocolSupport plugin (Fix issue #29)

---

patches/server/0067-Add-config-option-for-logging-player-ip-addresses.patch

Backport of [Paper-0753: Add config option for logging player ip addresses](https://github.com/PaperMC/Paper/blob/b3b04f2ca109979cd9aebd8e7859decbeeba10d4/patches/server/0753-Add-config-option-for-logging-player-ip-addresses.patch).
Closes #32

Add config option for logging player ip addresses

---

patches/server/0004-Backport-modern-tick-loop.patch
patches/server/0012-Consolidate-flush-calls-for-entity-tracker-packets.patch
patches/server/0016-Optimize-World-Time-Updates.patch
patches/server/0017-Configurable-time-update-frequency.patch
patches/server/0022-EntityMoveEvent.patch
patches/server/0030-Cleanup-allocated-favicon-ByteBuf.patch
patches/server/0036-Backport-PlayerProfile-API.patch
patches/server/0040-Use-TerminalConsoleAppender-for-console-improvements.patch
patches/server/0047-Only-process-BlockPhysicsEvent-if-a-plugin-has-a-lis.patch
patches/server/0072-Skip-updating-entity-tracker-if-server-is-empty.patch

Changes:
1: Cleanup
2: Don't display overload message after server startup (https://github.com/Wind-Development/WindSpigot/commit/1b9d1a7926e68ff4a0da8ef21deba6cf60de22ac & https://github.com/Wind-Development/WindSpigot/commit/7190cd5733f8a7246a3588b336200c3776784589)
3: Add missing change in az() method (https://github.com/Wind-Development/WindSpigot/commit/b735e19966c7119ce92e510f915d0c58de705374#diff-a1d5ab453d81fa6035e2465e8e84ffdb13fba514310caee493a15e71afad72cbR1593)
Fixes #95

Modern tick loop cleanup and fixes

---

patches/server/0010-Optimize-Network-Manager-and-add-advanced-packet-sup.patch

when testing with bots 100-200 with movement and swing options
saw that the netty threads where always very busy/looked like getting overloaded from profiling
upon further investigation it looked like these parts where ported over from later versions
and now they aren't overloaded 
even teleporting 100 bots to your location and they instantly started to move again on client
compared to the server almost crashing before from overloading on the flushing of the queued packets that where waiting to be processed or be sent back
also these changes where in the spotted patch so they might have been missed/overlooked

add overlooked parts of optimize network patch

---

patches/server/0086-Fix-Entity-Tracker-Rounding.patch
patches/server/0087-Fix-Entity-Tracker-Rounding.patch

the vanilla entity tracker always floors when converting coordinates to an int before sending them to the client, this patch rounds properly so player positions are slightly more accurate clientside. more info here: https://www.youtube.com/watch?v=Ba2TCTf8_nU

Fix Entity Tracker Rounding

---

patches/server/0036-Backport-PlayerProfile-API.patch
patches/server/0061-Add-Player-sendEquipmentChange.patch
patches/server/0069-Fix-setFlying-Toggle.patch

Currently breaking are potion effects and the XP bar, both are now being resent to make the client know about them again.
Ported from PaperMC/Paper#9080

Properly resync player on Player#setPlayerProfile

---

patches/api/0025-Add-a-call-helper-to-Event.patch
patches/server/0005-Backport-PlayerHandshakeEvent-from-Paper.patch
patches/server/0007-Add-Unix-domain-socket-support.patch
patches/server/0022-EntityMoveEvent.patch
patches/server/0023-Player-Chunk-Load-Unload-Events.patch
patches/server/0037-Sound-events.patch
patches/server/0068-Backport-TabCompleteEvent-and-AsyncTabCompleteEvent.patch
patches/server/0075-Avoid-loading-chunks-in-multiple-places.patch
patches/server/0078-Fix-MC-117075-TE-Unload-Lag-Spike.patch
patches/server/0080-Optimize-tnt-entity-and-falling-block-movement.patch
patches/server/0081-Optimize-Captured-TileEntity-Lookup.patch
patches/server/0085-Implement-SpawnerPreSpawnEvent.patch
patches/server/0087-Optimize-Light-Recalculations.patch
patches/server/0088-Optimize-armor-stands.patch

These changes are from PR #147 , I decided to separate them because they are small changes that can be merged quickly

Add a call helper to Event

---

build-logic/build.gradle.kts
build-logic/src/main/kotlin/ArchiveName.kt
build-logic/src/main/kotlin/RemapTask.kt
build-logic/src/main/kotlin/paperclip.gradle.kts
patches/server/0003-Setup-Gradle-project.patch
patches/server/0006-Update-to-Netty-4.1.x.patch
patches/server/0014-PandaSpigot-Configuration.patch
patches/server/0040-Use-TerminalConsoleAppender-for-console-improvements.patch

This patch re-introduces the remapping of `_INVALID_` deprecated methods performed by upstream, as well as transforming old `int` health-related setters to have the synthetic modifier (plugins should be using the `double` methods).
This is done to provide binary compatibility with plugins built against very old versions of the Bukkit API.
This implementation for PandaSpigot uses a modified version of the [`RemapTask` in `gradle-specialsource`](https://github.com/typst-io/gradle-specialsource/blob/8b038c46d1b9e8a6a523ad7278c4b07b078650dd/src/main/kotlin/io/typecraft/gradlesource/RemapTask.kt), licensed under Apache 2.0.
Fixes #7, #152, #159, #174, #178

Remap final jar using Spigot deprecation mappings

---

patches/server/0100-Add-Stricter-Client-Sign-limits.patch

Ported from [Paper 1.12.2 patch 0374](https://github.com/PaperMC/Paper/blob/ver/1.12.2/Spigot-Server-Patches/0374-Add-Stricter-Client-Sign-limits.patch)
Helps to mitigate exploits where clients can send extremely long components that when turned into strings later and parsed with regex can cause the server to hang.

Add stricter client sign limits

---

patches/server/0003-Setup-Gradle-project.patch
patches/server/0006-Update-to-Netty-4.1.x.patch
patches/server/0015-PandaSpigot-Configuration.patch
patches/server/0040-Use-TerminalConsoleAppender-for-console-improvements.patch

The "disable.watchdog" flag does not exist in 1.8

Remove redundant code

---

patches/server/0040-Use-TerminalConsoleAppender-for-console-improvements.patch

Fix #204
I wasted a lot of time trying to find the problem, which was so obvious, initially I tried to put WHITE here like in Paper, but I put the ) in the wrong place and that's why it didn't work lol

Fix console messages being black by default

---

patches/server/0004-Backport-modern-tick-loop.patch
patches/server/0013-Consolidate-flush-calls-for-entity-tracker-packets.patch
patches/server/0017-Optimize-World-Time-Updates.patch
patches/server/0018-Configurable-time-update-frequency.patch
patches/server/0023-EntityMoveEvent.patch
patches/server/0030-Cleanup-allocated-favicon-ByteBuf.patch
patches/server/0035-Optimize-Network-Queue.patch
patches/server/0036-Backport-PlayerProfile-API.patch
patches/server/0040-Use-TerminalConsoleAppender-for-console-improvements.patch
patches/server/0047-Only-process-BlockPhysicsEvent-if-a-plugin-has-a-lis.patch
patches/server/0071-Skip-updating-entity-tracker-if-server-is-empty.patch

Changes:
- Moved the getMillis() and getNanos() methods to the SystemUtils class (as it is in 1.13+)
- Fix the aL()/ThreadWatchDog method returning/using the wrong variable;
* To understand more about this bug:
By default, Minecraft has the "nextTick" variable called "ab", with the Modern Tick Loop (which we backported from WindSpigot) it added a redundant variable called "nextTickTime", and the aL() method continued using the old variable "ab", this bug is caused by WindSpigot itself, since in the original pullrequest for NachoSpigot it does not exist because the author deleted the "ab" variable and used the "nextTickTime" variable in the method, in PandaSpigot I did the opposite and removed the nextTickTime and used "ab" since it is unnecessary to add a new variable to do the same thing …

Fix and cleanup modern tick loop

---

.gitmodules

Paper will soon move all version branches from 1.8 to 1.21.3 to the 'Paper-archive' repo as part of their hard fork process.
See https://forums.papermc.io/threads/the-future-of-paper-hard-fork.1451/ for details

Update Paper submodule to point to archive repository

---

patches/server/0106-Add-additional-catch-to-handle-NPE-on-usercache-load.patch

It is common for people to ask for help on discord due to corrupted usercache throwing NPE, now the server will deal with it

Add additional catch to handle NPE on usercache loading

---

panda
scripts/applyPatches.sh
scripts/build.sh

- Revert my change that made Panda patches only apply when running ./panda patch, now they will be applied again when using ./panda setup
- Small improvements in build.sh:
Added a message if any script fails
Removed argument checking (It used to be useful because ./panda patch runs this script, a few commits ago I changed it to run applyPatches.sh directly)
Removed cd "$basedir", the "panda" script already does this

[skip ci] Small adjustments to the scripts

---

scripts/build.sh
scripts/importmcdev.sh
scripts/init.sh

This pull request simply reverts a change from the "Update scripts for NMS repackaging" commit made in Paper 1.16, from which we inherited the scripts. This change makes sense in the context of repackaged packages, since there are multiple subpackages within nms-patches, but for us it doesn't, since the script just tries to create the "src/main/java/net/minecraft/server" directory multiple times, and some small changes.

[skip ci] Try creating the directory only once

---

patches/server/0112-Fix-collision-detection-of-entities-with-blocks.patch
patches/server/0112-Fix-collision-detection-with-blocks.patch

Supersedes #322
Technically, what we fixed here is the collision detection of entities with blocks
Explanation:
the server sets the fallDistance to 0 when it detects that the player has collided with the web, so the player does not take damage, however, CB during the 1.5.1 era added an optimization to avoid calling the movement logic if the entity was not actually moving, but this caused problems with portals, which led CB to move the collision detection above the check, which caused the current problem. I reverted this to vanilla logic, which fixes the problem, about the optimization: It should not have any negative performance impact, since in the original commit it is made clear, that the method is almost never called without the entities actually moving.

Fix #278: Taking damage when falling into web from a height >=24 blocks

---

patches/server/0111-Fix-GH-276-Item-durability-desync-when-some-events-a.patch

Reverts part of the fix in 62cddd2492be92c56e67c962bbe045d064d36428

Fix animation desync when hitting a player and defending with an unbreakable sword

---

patches/server/0107-Backport-modern-tick-loop-system.patch

We're currently calculating System.nanoTime() / 1000 - nextTickTime;
However, nextTickTime in 1.8 returns System.currentTimeMillis(), which leads to an impossible calculation since they are two different measurement systems. In 1.13, this doesn't happen, since nextTickTime returns System.nanoTIme() / 1000. The fix is ​​simple: just separate curTime and use getCurrentTimeMillis() instead.
Before:
```java
[18:17:31 INFO]: System: -1757259012986
[18:17:31 INFO]: System: -1757259012988
[18:17:31 INFO]: System: -1757259012988
[18:17:31 INFO]: System: -1757259012988
[18:17:31 INFO]: System: -1757259012988
[18:17:31 INFO]: System: -1757259012987
[18:17:31 INFO]: System: -1757259012988
[18:17:31 INFO]: System: -1757259012988
[18:17:31 INFO]: System: -1757259012988
[18:17:31 INFO]: System: …
```

Fix overloaded server check

---

patches/api/0027-Adventure-API.patch
patches/server/0114-Adventure-API.patch

This pull request adds native support for [Kyori Adventure](https://docs.advntr.dev/). This (hopefully) resolves #156. 
See #352 for history
<details>
<summary>Overview of changes</summary>
- #### General changes
- CommandSender (and Player) can use Component and MiniMessage strings in messages
- Permissible supports TriState values
- Entity custom name supports Component
- #### Player changes
- Send Tablist Headers / Footers, Titles using Adventure
- Getters and Setters for displayName and playerListName with Component
- Kick with Component
- #### Inventory and items
- BookMeta title, author, and pages supports Component
- ItemMeta displayName and lore supports Component
- Inventory title supports Component
- #### Scoreboard 
- Team displayName, prefix, and suffix support Component
- …

Native Kyori Adventure API
