patches/server/0053-Disconnect-for-payload-errors.patch

Disconnect for payload errors

---

patches/server/0056-Faster-redstone-torch-rapid-clock-removal.patch

Needs testing but should work without problems.

Backport "Faster redstone torch rapid clock removal" patch

---

patches/server/0059-Shame-on-you-mojang.patch

Original patch link: https://github.com/PaperMC/Paper/blob/ver/1.12.2/Spigot-Server-Patches/0202-Shame-on-you-Mojang.patch

Backport "Shame on you mojang" patch

---

patches/server/0063-Cache-chunk-coordinations.patch

Original commit and author in: https://github.com/CobbleSword/NachoSpigot/commit/76966334a9e509f45a3272d32dc8d85de5d41957

Backport "[InsanePaper-269] Cache chunk coordinations" patch by @LewUwU

---

.github/workflows/build.yml
.github/workflows/check.yml
patches/api/0003-Setup-Gradle-project.patch
scripts/importmcdev.sh

* Added `check` workflow that runs on PRs.
* Only run `build` workflow on master.
* Upgraded `checkout` and `setup-java` to v3
* Use `gradle-cache-action` for Maven/Gradle caching.
* Hide API javadoc warnings.

Refactor Actions workflows

---

patches/api/0020-Backport-TabCompleteEvent-and-AsyncTabCompleteEvent.patch
patches/server/0068-Backport-TabCompleteEvent-and-AsyncTabCompleteEvent.patch

Backport TabCompleteEvent and AsyncTabCompleteEvent

---

patches/server/0002-Rebrand.patch
patches/server/0003-Setup-Gradle-project.patch
patches/server/0006-Update-to-Netty-4.1.x.patch
patches/server/0031-Optimize-BlockPosition-helper-methods.patch
patches/server/0040-Use-TerminalConsoleAppender-for-console-improvements.patch
patches/server/0043-Add-Channel-initialization-listeners.patch

1 - Re-adds a log4j update diff that I accidentally removed in my first contribution
2 - Cleanup patch and add diff to rebrand to PandaSpigot in crash-reports
3 - Adds a diff that is missing from 1 patch

Cleanup and add some diff's that are missing

---

patches/server/0006-Update-to-Netty-4.1.x.patch
patches/server/0014-PandaSpigot-Configuration.patch
patches/server/0040-Use-TerminalConsoleAppender-for-console-improvements.patch

Haven't found any issues why we shouldn't keep this up to date 
cause the current one is more then a year old 😅

Update Netty Dependency to latest version

---

patches/server/0081-Optimize-Captured-TileEntity-Lookup.patch

Continuation of PR #61
(I was too lazy to fix conflicts)

Optimize Captured TileEntity Lookup

---

patches/server/0084-Book-security-improvements.patch
patches/server/0084-Security-fixes-for-reported-book-issues.patch

Add security checks to prevent exploits

Book security improvements

---

patches/server/0006-Update-to-Netty-4.1.x.patch
patches/server/0014-PandaSpigot-Configuration.patch
patches/server/0040-Use-TerminalConsoleAppender-for-console-improvements.patch

https://netty.io/news/2022/12/12/4-1-86-Final.html

Update netty to 4.1.86.Final

---

patches/server/0075-Avoid-loading-chunks-in-multiple-places.patch

somehow this borke it 
even tried to move the null check inside the isOccluding so it 100% wouldn't break the whole method but still seemed to not work
don't have much time now to debug it more now

fixes spawning of mobs

---

patches/server/0070-Fix-AIOOBE-in-inventory-handling.patch

could be best to have it in both places somehow I messed up the location of the check since the part look very similar also with a -999 check
maybe later have both checks in but this is the right location for the check
fixes #89

change location of the < 0 check for aiobe

---

patches/server/0086-Remove-DataWatcher-Locking.patch

Backported from https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/CraftBukkit-Patches/0107-Remove-DataWatcher-Locking.patch?at=version%2F1.14.4

Remove DataWatcher Locking

---

patches/server/0015-Configurable-knockback.patch

mechoriet forgot a part of the config

Use default vanilla knockback settings

---

patches/server/0088-Optimize-Light-Recalculations.patch
patches/server/0089-Optimize-armor-stands.patch

Ported from: https://github.com/TacoSpigot/TacoSpigot/blob/version/1.8.8/PaperSpigot-Server-Patches/0010-Optimize-armor-stands.patch

Optimize armor stands

---

patches/server/0009-Optimize-Network-Manager-and-add-advanced-packet-sup.patch
patches/server/0010-Allow-controlled-flushing-for-network-manager.patch
patches/server/0011-Consolidate-flush-calls-for-entity-tracker-packets.patch
patches/server/0012-Optimise-non-flush-packet-sending.patch
patches/server/0013-Disable-Explicit-Network-Manager-Flushing.patch
patches/server/0027-Avoid-blocking-on-Network-Manager-creation.patch
patches/server/0038-Optimize-VarInt-reading-and-writing.patch
patches/server/0043-Add-Channel-initialization-listeners.patch
patches/server/0052-Add-packet-limiter-config.patch
patches/server/0067-Add-config-option-for-logging-player-ip-addresses.patch
patches/server/0072-Skip-updating-entity-tracker-if-server-is-empty.patch

solves a problem when npc's get out of sight and go back to it they don't become visible again
and probably also solves other issues related to entity tracking
closes #118 
closes #6 
Fixes #27

Fixes npc not showing after going out of range

---

patches/server/0006-Update-to-Netty-4.1.x.patch
patches/server/0014-PandaSpigot-Configuration.patch
patches/server/0040-Use-TerminalConsoleAppender-for-console-improvements.patch

had no issues in my testing so far
with a lot of bots that moved

update netty to 4.1.91

---

patches/server/0075-Avoid-loading-chunks-in-multiple-places.patch

I got this fix from PR 74, but the other PR has other changes, and I need more time to analyze them, so I separated this change in this PR to be implemented faster

Fix chest checking

---

patches/server/0100-Fix-custom-anvil-inventory.patch

Fix custom anvil inventory

---

patches/server/0052-Add-packet-limiter-config.patch

Splitted from the PR https://github.com/hpfxd/PandaSpigot/pull/147, thanks to mechoriet

Fix compile warning

---

patches/server/0012-Allow-controlled-flushing-for-network-manager.patch

Tested on a server with 150-160 players, no issues

Readd missing diff

---

patches/server/0037-Sound-events.patch

Fix entity returning null on EntitySoundEvent

---

patches/server/0040-Use-TerminalConsoleAppender-for-console-improvements.patch

https://github.com/hpfxd/PandaSpigot/pull/240#issuecomment-2417428293

Use ChatColor.RESET instead of ChatColor.WHITE

---

patches/server/0004-Backport-modern-tick-loop.patch
patches/server/0013-Consolidate-flush-calls-for-entity-tracker-packets.patch
patches/server/0017-Optimize-World-Time-Updates.patch
patches/server/0018-Configurable-time-update-frequency.patch
patches/server/0023-EntityMoveEvent.patch
patches/server/0030-Cleanup-allocated-favicon-ByteBuf.patch
patches/server/0036-Backport-PlayerProfile-API.patch
patches/server/0040-Use-TerminalConsoleAppender-for-console-improvements.patch
patches/server/0047-Only-process-BlockPhysicsEvent-if-a-plugin-has-a-lis.patch
patches/server/0071-Skip-updating-entity-tracker-if-server-is-empty.patch

* Readd an accidentally removed line that marks "hasTicket" as true
* Add missing @Override annotation

Minor tweaks to the modern tick loop

---

patches/server/0108-Fix-entities-going-out-of-sight.patch

Fix https://github.com/hpfxd/PandaSpigot/issues/244

Fix entities going out of sight

---

patches/server/0109-Fix-SPIGOT-2622-Only-one-player-receiving-the-server.patch

Fix only one player receiving the server shutdown message

---

panda
scripts/applyPatches.sh
scripts/build.sh

Split from an old mechoriet pullrequest (#114), I just improved the logic a little

Script improvements

---

patches/server/0042-Add-Channel-initialization-listeners.patch

See https://github.com/kangarko/ChatControl/issues/3091#issuecomment-2714212790

Fix #299: Update adventure-key to latest version

---

patches/server/0001-Fix-Decompilation-errors.patch
patches/server/0113-Remove-duplicate-null-check-for-chunk-in-unloadChunk.patch

Remove duplicate null check for chunk in unloadChunks method, we already checked above

Optimize ChunkProviderServer#unloadChunks
